# Generated by Django 5.2 on 2025-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('admin', 'Administrator')], default='admin', max_length=20),
        ),
    ]
