# Generated by Django 4.2.13 on 2025-12-02 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('device_type', models.CharField(blank=True, max_length=500, null=True)),
                ('browser_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor')),
            ],
        ),
    ]
