# Generated by Django 5.2 on 2025-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
