# Generated by Django 5.2 on 2025-12-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'permissions': [('can_list_visitors', 'view_list_visitors')]},
        ),
    ]
