# Generated by Django 5.2 on 2025-12-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visitor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'permissions': [('can_list_visitors', 'Can view list Visitor')]},
        ),
    ]
