# Generated by Django 5.2 on 2025-12-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_alter_visitor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'permissions': [('view_list_visitor', 'Can view list visitor')]},
        ),
    ]
