# Generated by Django 4.2.13 on 2025-12-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='settings/platform/', verbose_name='Dark Logo')),
                ('light_logo', models.ImageField(blank=True, null=True, upload_to='settings/platform/', verbose_name='Light Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/platform/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(default='Africa/Casablanca', max_length=100)),
                ('currency', models.CharField(default='MAD', max_length=10)),
                ('currency_symbol', models.CharField(default='dh', max_length=10, verbose_name='Currency Symbol')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Allow User Registration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_cors', models.BooleanField(default=True)),
                ('allowed_cors', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='My Platform', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok_pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp URL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok URL')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
                'verbose_name_plural': 'Social Media Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_whatsapp', models.BooleanField(default=True)),
                ('number_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('contact_vocal', models.BooleanField(default=True)),
                ('number_vocal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Call Number')),
                ('contact_email', models.BooleanField(default=True)),
                ('show_profile', models.BooleanField(default=True, verbose_name='Show Profile Publicly')),
                ('show_contact_info', models.BooleanField(default=True, verbose_name='Show Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'Users Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
